let Letters = dynamic(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]);
let Digits = dynamic(["2", "2", "2", "3", "3", "3", "4", "4", "4", "5", "5", "5", "6", "6", "6", "7", "7", "7", "7", "8", "8", "8", "9", "9", "9", "9"]);
noah_customers
| extend last_name = toupper(split(name, " ")[-1])
| project name, last_name, phone
| extend changed_last_name = replace_strings(last_name, Letters, Digits), clean_number = replace_string(phone, "-", "")
| where changed_last_name == clean_number
